- name: set nginx deploy spec
  when: nginx_deploy_spec is not defined
  vars:
    annotations: "{{ nginx_deploy_spec_annotations | default(false) }}"
    extra_labels: "{{ nginx_deploy_spec_extra_labels | default(false) }}"
  set_fact:
    nginx_deploy_spec: "{{ lookup('template', nginx_deploy_spec_template) }}"

- name: nginx deploy resource definition
  vars:
    kind: Deployment
    k8s_state: "{{ nginx_deploy_state | default(nginx_state) }}"
    k8s_wait: "{{ nginx_deploy_wait | default(true) }}"
    k8s_wait_timeout: "{{ nginx_deploy_wait_timeout | default(120) }}"
    template: "{{ deploy_template }}"
    metadata_name: "{{ nginx_deploy }}"
    annotations: "{{ nginx_deploy_annotations | default(false) }}"
    connects_to: "{{ php_fpm_appname }}"
    runtime: nginx
    deploy_spec: "{{ nginx_deploy_spec }}"
  import_tasks: k8s/object.yml

- name: save nginx deploy resource definition task output
  set_fact:
    k8s_nginx_deploy: "{{ k8s_object_task }}"
