- name: nginx route resource definition
  when:
    - expose_type is defined and expose_type
    - "(expose_type | lower) == 'route'"
  vars:
    k8s_kind: Route
    k8s_state: "{{ nginx_route_state | default(nginx_state) }}"
    template: "{{ route_template }}"
    metadata_name: "{{ nginx_route }}"
    annotations: "{{ nginx_route_annotations | default(false) }}"
    route_spec: "{{ nginx_route_spec }}"
  import_tasks: k8s/object.yml

- name: save nginx route resource definition task
  set_fact:
    k8s_nginx_route: "{{ k8s_object_task }}"
