- name: run moodle status script
  register: status_moodle_task
  changed_when: false
  script: "{{ moodle_status_script }}{{ ' -v' if moodle_status_version else '' }}{{ ' -u' if
    moodle_status_usage else '' }}{% if moodle_status_checks is defined and
    moodle_status_checks %} -c='{{ moodle_status_checks }}'{% endif %}"

- name: set moodle status from script output
  import_tasks: k8s/status.yml
  when: status_moodle_task.stdout is defined and status_moodle_task.stdout
  delegate_to: localhost
  vars:
    k8s_status_status: "{{ status_moodle_task.stdout | from_json }}"
