- name: postgres service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ postgres_service_state | default(postgres_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ postgres_service }}"
    service_spec: "{{ postgres_service_spec }}"
  import_tasks: k8s/object.yml

- name: save postgres service resource definition task
  set_fact:
    k8s_postgres_service: "{{ k8s_object_task }}"
