- name: php-fpm service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ php_fpm_service_state | default(php_fpm_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ php_fpm_service }}"
    service_spec: "{{ php_fpm_service_spec }}"
  import_tasks: k8s/object.yml

- name: save php-fpm service resource definition task
  set_fact:
    k8s_php_fpm_service: "{{ k8s_object_task }}"
