- name: remove remaining jobs and its pods of moodle cronjob
  loop:
    - Job
    - Pod
  vars:
    k8s_definition: "{{ lookup('k8s', kind=item, namespace=meta_namespace,
      label_selector='app=' + metadata_app ) }}"
    k8s_state: absent
  when:
    - (k8s_definition | length) > 0
    - "(moodle_cronjob_state | default(moodle_state)) == 'absent'"
  include_tasks: k8s/object.yml
