- import_tasks: instantiated.yml

- import_tasks: ready.yml

- name: "set {{ meta_name }} status"
  when: set_ready_condition is defined or
        set_instantiated_condition is defined
  vars:
    k8s_status_conditions: "{{ set_instantiated_condition | default([]) +
      set_ready_condition | default([]) }}"
  include_tasks: k8s/status.yml
