---
- name: refresh dynamic inventory
  meta: refresh_inventory

- name: get pods information
  k8s_info:
    kind: Pod
    namespace: "{{ meta_namespace }}"
    label_selectors: "{{ label_selectors if label_selectors is defined else omit }}"
    field_selectors: "{{ field_selectors if field_selectors is defined else omit }}"
  until: "{{ k8s_info_until | default(true) }}"
  delay: "{{ k8s_info_delay | default(0)  }}"
  retries: "{{ k8s_info_retries | default(0) }}"
  register: k8s_info_pods

- name: add hosts to inventory
  with_subelements:
    - "{{ k8s_info_pods.resources }}"
    - status.containerStatuses
  when:
    - item.1.ready
  changed_when: false
  no_log: "{{ add_host_no_log | default(omit) }}"
  add_host:
    groups:
      - "{{ item.0.metadata.name | replace('-', '_') }}"
      - pods
      - "{{ item.0.metadata.labels.app | replace('-', '_') }}"
      - "{{ item.0.metadata.labels['app.kubernetes.io/component'] | replace('-', '_') }}"
      - "{{ meta_namespace | replace('-', '_') }}"
    name: "{{ item.0.metadata.name }}__{{ item.1.name }}"
    ansible_kubectl_pod: "{{ item.0.metadata.name }}"
    ansible_kubectl_container: "{{ item.1.name }}"
    ansible_kubectl_namespace: "{{ meta_namespace }}"
    ansible_connection: kubectl
    ansible_remote_tmp: /var/tmp/.ansible
    state: "{{ item.1.state }}"
