- name: keep config.php update without need of pod restart
  when: moodle_config_autosync
  block:
  - name: check config.php exists from src
    stat:
      path: "{{ moodle_config_path }}/config.php"
    register: moodle_config_autosync_file

  - name: copy config.php to dest
    when: moodle_config_autosync_file.stat.exists
    copy:
      remote_src: true
      src: "{{ moodle_config_path }}/config.php"
      dest: "{{ moodle_app }}/config.php"
      mode: 0660
